### ISSUE TITLE
create clutter objects

### ISSUE THREAD

**Issue by Samuel-Cook** [UoSGamesGroups/level-6-l6-group-6#64]
create the following clutter objects

- [x] Coffee
- [x] Food Cans
- [x] Bottles of water (1920?)
- [x] Plates
- [ ] Utensils

**Comment by Anthony-Brame** [comment]
Have 3 out of 5 models done, untextured. will upload later on once all 5 models are done, then start texturing + I shall be then also making a for utensils.

**Comment by Samuel-Cook** [comment]
finish textures
